recipe: default.v1
language: zh

pipeline:
  # Language Model 语言模型
  # - name: MitieNLP # MITIE词向量语言模型
  #  model: "data/total_word_feature_extractor_zh.dat"

  # Tokenizer 分词器
  - name: JiebaTokenizer # jieba分词器

  # Featurizer 特征化器
  - name: LanguageModelFeaturizer
    model_name: bert
    model_weights: bert-base-chinese

  # Intent Classifier 意图分类器
  # - name: MitieIntentClassifier

  # Entity Extractor 实体提取器
  # - name: MitieEntityExtractor

  # (可选) Combined Intent Classifiers and Entity Extractors 上面两者的结合
  - name: DIETClassifier
  
  # Selectors 选择器
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true

policies:
   - name: MemoizationPolicy
   - name: RulePolicy
   - name: TEDPolicy
     epochs: 100
     constrain_similarities: True
   - name: UnexpecTEDIntentPolicy
     max_history: 5
     epochs: 100
   - name: TEDPolicy
     max_history: 5
     epochs: 100
     constrain_similarities: true